import frame_data
class Dict:
    def __init__(self):
        self.d = {}
        self.d["person"] = frame_data
        self.d["bicycle"] = frame_data
        self.d["car"] = frame_data
        self.d["motorcycle"] = frame_data
        self.d["airplane"] = frame_data
        self.d["bus"] = frame_data
        self.d["train"] = frame_data
        self.d["boat"] = frame_data
        self.d["traffic light"] = frame_data
        self.d["fire hydrant"] = frame_data
        self.d["street sign"] = frame_data
        self.d["stop sign"] = frame_data
        self.d["parking meter"] = frame_data
        self.d["bench"] = frame_data
        self.d["bird"] = frame_data
        self.d["cat"] = frame_data
        self.d["dog"] = frame_data
        self.d["horse"] = frame_data
        self.d["sheep"] = frame_data
        self.d["cow"] = frame_data
        self.d["elephant"] = frame_data
        self.d["bear"] = frame_data
        self.d["zebra"] = frame_data
        self.d["giraffe"] = frame_data
        self.d["hat"] = frame_data
        self.d["backpack"] = frame_data
        self.d["umbrella"] = frame_data
        self.d["shoe"] = frame_data
        self.d["eye glasses"] = frame_data
        self.d["handbag"] = frame_data
        self.d["tie"] = frame_data
        self.d["suitcase"] = frame_data
        self.d["frisbee"] = frame_data
        self.d["skis"] = frame_data
        self.d["snowboard"] = frame_data
        self.d["sports ball"] = frame_data
        self.d["kite"] = frame_data
        self.d["baseball bat"] = frame_data
        self.d["baseball glove"] = frame_data
        self.d["skateboard"] = frame_data
        self.d["surfboard"] = frame_data
        self.d["tennis racket"] = frame_data
        self.d["bottle"] = frame_data
        self.d["plate"] = frame_data
        self.d["wine glass"] = frame_data
        self.d["cup"] = frame_data
        self.d["fork"] = frame_data
        self.d["knife"] = frame_data
        self.d["spoon"] = frame_data
        self.d["bowl"] = frame_data
        self.d["banana"] = frame_data
        self.d["apple"] = frame_data
        self.d["sandwich"] = frame_data
        self.d["orange"] = frame_data
        self.d["broccoli"] = frame_data
        self.d["carrot"] = frame_data
        self.d["hot dog"] = frame_data
        self.d["pizza"] = frame_data
        self.d["donut"] = frame_data
        self.d["cake"] = frame_data
        self.d["chair"] = frame_data
        self.d["couch"] = frame_data
        self.d["potted plant"] = frame_data
        self.d["mirror"] = frame_data
        self.d["dining table"] = frame_data
        self.d["window"] = frame_data
        self.d["desk"] = frame_data
        self.d["toilet"] = frame_data
        self.d["door"] = frame_data
        self.d["tv"] = frame_data
        self.d["laptop"] = frame_data
        self.d["mouse"] = frame_data
        self.d["remote"] = frame_data
        self.d["keyboard"] = frame_data
        self.d["cell phone"] = frame_data
        self.d["microwave"] = frame_data
        self.d["oven"] = frame_data
        self.d["toaster"] = frame_data
        self.d["sink"] = frame_data
        self.d["refrigerator"] = frame_data
        self.d["blender"] = frame_data
        self.d["book"] = frame_data
        self.d["clock"] = frame_data
        self.d["vase"] = frame_data
        self.d["scissors"] = frame_data
        self.d["teddy bear"] = frame_data
        self.d["hair drier"] = frame_data
        self.d["toothbrush"] = frame_data
        self.d["hair brush"] = frame_data
